### PR TITLE
#397: Sign SQLite/BLToolkit.Data.DataProvider.SQLite.4.csproj

### PR DESCRIPTION
**Pull request by WebSerGe**
Sign BLToolkit.Data.DataProvider.SQLite.4

### CODE REVIEW

**Comment by jogibear9988** [comment]
Is it only missing in Sqlite, or in the other Providers too? If so, could you also fix?

**Comment by WebSerGe** [comment]
Other providers too. Ok, I will fix all of them.

**Comment by WebSerGe** [comment]
All providers are signed, note I have not touched 3.csproj.
Example of BLToolkit.Data.DataProvider.DB2.4.dll:
`BLToolkit.Data.DataProvider.DB2.4, Version=4.3.7.0, Culture=neutral, PublicKeyToken=b1d3f6ab3aadaca3`

**Comment by WebSerGe** [comment]
Link to original issue https://github.com/igor-tkachev/bltoolkit/issues/397

**Pull request merged**
