### PR TITLE
Fix enum convertion in InsertBatch

### PR DESCRIPTION
**Pull request by Firebie**

### CODE REVIEW

**Comment by ili** [comment]
1) Please, can you provide tests to see what is fixed?
2) What is need for DbManagerTransactoin?

in any way, it is better to make one branch for each feature, and then to make pull request from this branch.

**Comment by Firebie** [comment]
DbManagerTransaction (copied from linq2db) purpose is to have its own transaction object and used like this:
  using (var tr = db.BeginTransaction())
  {
    // doing data changes
    tr.Commit();
  }

**Comment by ili** [comment]
Ok, I see...

How about tests on enum mapping? Or may be just code sample fails without this fix?

**Comment by Firebie** [comment]
Here is test to show usage of 'Fix enum convertion' - bltoolkit generates bad sql without it:

  public enum Enum1
  { 
    Zero = 0,
    One  = 1,
    Two  = 2,
  }

  public class TestEnum
  {
    public Enum1? Enum1;
  }

  using (var db = new Db())
  {
    var types = new [] { Enum1.One, Enum1.Two };

    var data = db.GetTable<TestEnum>()
      .Where(i => types.Contains(i.Enum1 ?? Enum1.One))
      .ToList();
  }


SELECT
	[i].[Enum1]
FROM
	[TestEnum] [i]
WHERE
	Coalesce([i].[Enum1], 1) IN (, )

**Comment by ili** [comment]
speacking about InsrtBatch, I'v implemented test, and it runs OK

```cs
		public enum TestEnum
		{
			First,
			Second,
			Third
		}

		[TableName("LinqDataTypes")]
		public class Table 
		{
			[PrimaryKey]
			public int       ID;
			public decimal   MoneyValue;
			[DbType(DbType.DateTime)]
			public DateTime? DateTimeValue;
			[DbType(DbType.DateTime)]
			public DateTime? DateTimeValue2;
			public bool?     BoolValue;
			public Guid?     GuidValue;
			public short?    SmallIntValue;
			[MapField("IntValue")]
			public TestEnum? EnumValue;
			public long?     BigIntValue;
		}


		[Test]
		public void InsertBatch3()
		{
			ForEachProvider(db =>
			{
				if (!(db is DbManager))
					return;

				var t = db.GetTable<Table>();

				t.Delete(_ => _.ID > 1000);

				((DbManager)db).InsertBatch(1, new[]
				{
					new Table { ID = 1003, MoneyValue = 0m, DateTimeValue = null,         BoolValue = true,  GuidValue = new Guid("ef129165-6ffe-4df9-bb6b-bb16e413c883"), SmallIntValue =  null, EnumValue = null },
					new Table { ID = 1004, MoneyValue = 0m, DateTimeValue = DateTime.Now, BoolValue = false, GuidValue = null,                                             SmallIntValue =  2,    EnumValue = TestEnum.Second },
				});

				foreach (var e in t.Where(_ => _.ID > 1000))
				{
					if (e.EnumValue != null)
						Assert.AreEqual(TestEnum.Second, e.EnumValue);
				}

				t.Delete(_ => _.ID > 1000);
			});
		}
```

**Comment by ili** [comment]
Mostly I'm not sure that it is a good idea to use the `Map` class, because it uses `DefaultMappingSchema` in 99% I think there are no difference, but...

**Comment by Firebie** [comment]
It was a problem for 'Fix enum convertion in InsertBatch', but now I can't find what cases it.

**Pull request merged**
