### PR TITLE
Replaced odp.net.managed with Oracle.ManagedDataAccess

### PR DESCRIPTION
**Pull request by yallie**
Issue #382.

### CODE REVIEW

**Comment by ili** [comment]
Cool! I'll review & merge it in 2 days

**Comment by ili** [comment]
Just package update and no tests are broken? Miracle? :)

**Comment by yallie** [comment]
Why a miracle? Oracle usually doesn't change much between versions.
My own stuff works fine with this provider, but I haven't tried
running BLToolkit's own tests.

Just can't find the instructions how to set up the database for tests. I thought
of these scripts in `/Data/Create Scripts` directory, but they seem to create
empty schema and I can't find where do I get the sample data for unit tests.
Would you kindly suggest where do I get the rest?

Also, I see that ManagedOracle connection string is commented out in the config file:
https://github.com/igor-tkachev/bltoolkit/blob/master/UnitTests/Linq/App.config#L57
Perhaps it's because this provider is known to have unresolved issues?
(I myself use it for a few years, and it seems to work just fine though).

**Comment by ili** [comment]
Really I have not tested OracleManaged too...

**Comment by yallie** [comment]
So what about BLToolkit tests in general? Is there some kind of database setup guide?
I started using PostgreSQL data provider and I see problems in the generated SQL.
Date/time arithmetic doesn't yield the proper SQL expressions.

I'd like to run the standard tests, add a failing test for my case, try to fix it, etc. as usual.
But when I create a database via provided SQL scripts, I got all standard tests failing.
Please point me in the right direction!

Thanks

**Comment by ili** [comment]
Are you sure of using BLT? it is better to start new projects with linq2db.

Speaking about standard tests - only Linq tests are well designed to run with different db.

Just create UserDataProviders.txt in linq tests folder (can be copied from DefaultDataProviders.txt) and write there a line:
ProviderName * ConnectionString 

Database should exist, all tables and other relations would be created automatically

**Comment by ili** [comment]
To run all other tests you should build them with conditional symbols like Oracle, Firebird, not sure if they are adopted to run with Postgre, but most of them should succed just sitting proper connection string in app.config.
DB & tables should be created with script manually

**Comment by yallie** [comment]
Thanks Ilya!

>Speaking about standard tests - only Linq tests are well designed to run with different db.

So, all I need is to create a database with tabkes, supply valid connection
string and run all tests from start to finish, so they can insert the data?
Looks like that I was missing: I was trying to execute LINQ tests selectively
using TestDriven.NET plugin.

>Are you sure of using BLT? it is better to start new projects with linq2db.

My project is not new, though I'd be glad to upgrade it to linq2db.
Perhaps you can clarify a few points to me?

What stops me is that we extensively use raw SQL queries along with LINQ.
First, there are lots of vendor-specific stuff not available with LINQ, such as
windowing functions, CONNECT BY, ROLLUP BY CUBE, to name a few.
I'm not sure if I can run raw SQL using linq2db just like with BLToolkit?
Second, we rely on Oracle array binding to insert large amounts of data,
which is available in BLToolkit (in fact, it's my own PR a few years ago),
but as far as I understand, not implemented in linq2db.

**Comment by ili** [comment]
About tests - there is Create test, it runs table creations script and fills data, so if you are running separate test you need to run it first. Also you should enable SQLite and run Create for it.

About linq2db you can run raw sql with it with `db.Execute(...)` extension method.

Also `BulkCopy` is supported for big data insert. 

The problems of migration are:
* using EditableObjects & EditableAreay
* using DataAccessors (in general using abstract types)

All other stuff can be easily migrated

**Comment by yallie** [comment]
>About tests - there is Create test, it runs table creations script and fills data

Thanks, will try it!

>Also BulkCopy is supported for big data insert.

BLToolkit had this, too, but array binding is quite different, not about only inserts.
I guess I should discuss this further in linq2db repository.

>using EditableObjects & EditableAreay
>using DataAccessors (in general using abstract types)

But the LINQ provider itself is no different?
I guess everything supported by BLToolkit should work the same way?

**Comment by yallie** [comment]
>About tests - there is Create test, it runs table creations script and fills data

Awesome, it worked! Tested on PostgreSQL provider, all tests pass except one.
But the bug's in the test itself (hardcoded owner name "public" in the attribute).
Thanks Ilya for your help.

**Comment by yallie** [comment]
I finally got Oracle unit tests running, and lots of them fail due to invalid generated code, regardless of the Oracle data provider version. For example:

```c#
[Test]
public void ToDefaultChar()
{
	ForEachProvider(new[] { "Oracle", "DevartOracle", ProviderName.Firebird, ProviderName.PostgreSQL }, db => AreEqual(
		from t in    Types select Sql.Convert(Sql.DefaultChar, t.MoneyValue).InvariantDecimal().Trim(' ', '0', '.'),
		from t in db.Types select Sql.Convert(Sql.DefaultChar, t.MoneyValue).InvariantDecimal().Trim(' ', '0', '.')));
}
```

Generates

```sql
SELECT
    Cast(t.MoneyValue as Char) as c1
FROM
    LinqDataTypes t
```

Which is incorrect. Char type cannot be referred to without the size:

```sql
SELECT
    Cast(t.MoneyValue as Char(10)) as c1
FROM
    LinqDataTypes t
``` 

But these are surely separate bugs beyond the scope of this PR.

**Comment by yallie** [comment]
I can push my changes required for running
Oracle managed driver tests so they add up to this PR.
Should I?

**Comment by yallie** [comment]
>Just package update and no tests are broken? Miracle? :)

Ah, just noticed that this exact package is used in linq2db.
I guess it's safe to assume it's stable enough to use it in bltoolkit as well.

**Comment by ili** [comment]
I'll work on merging and updating package on Sunday, no time earlier :(

If you found some bug in PostgreSQL can you make the PR?

**Comment by yallie** [comment]
>I'll work on merging and updating package on Sunday, no time earlier :(

I made no changes to the code, only unit tests.
Unit tests currently pass. The dependency is already used in linq2db.
Why not just accept the PR via the Github UI?

>If you found some bug in PostgreSQL can you make the PR?

Sure, when I find and fix the bug.

**Comment by ili** [comment]
> Why not just accept the PR via the Github UI?
Just a rule "Run all tests before package publishing" :)

**Comment by yallie** [comment]
Ok, sorry, I wasn't aware that you publish a package on each PR.

**Comment by ili** [comment]
New package published https://www.nuget.org/packages/BLToolkit.Oracle.Managed

**Comment by yallie** [comment]
>If you found some bug in PostgreSQL can you make the PR?

Here you are: #393.
Looks like the bug has already been fixed in linq2db.

**Pull request merged**
